version: '3'

networks:
  sxcms:
    name: sxcms
    driver: bridge

volumes:
  db-data:

services:

  db:
    image: sastix/cmsmariadb:1.0
    container_name: sxcms-mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: sastixcms
      MYSQL_PASSWORD: sastixcms
      MYSQL_USER: sastixcms
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - sxcms