global:
    scrape_interval: 10s
  
scrape_configs:
    - job_name: 'nginx'
      metrics_path: '/metrics'
      scrape_interval: 5s
      static_configs:
        - targets: ['sxcms-nginx-prometheus-exporter:9113']

    - job_name: 'sastix-cms'
      metrics_path: '/actuator/prometheus'
      scrape_interval: 5s
      static_configs:
        - targets: ['sxcms:9082']