version: '3.7'

volumes:
    prometheus_data: {}

networks:
  sxcms-monitoring:
    external: true
    name: sxcms-monitoring

services:

  prometheus:
    image: prom/prometheus:v2.28.1
    container_name: sxcms-prometheus
    restart: always
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - sxcms-monitoring

  nginx-prometheus-exporter:
    image: nginx/nginx-prometheus-exporter
    container_name: sxcms-nginx-prometheus-exporter
    command: "-nginx.scrape-uri=http://sxcms-nginx:8080/stub_status"
    restart: always
    networks:
      - sxcms-monitoring
