version: '3'

networks:
  sxcms:
    name: sxcms
    external: true

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: sxcms-keycloak
    restart: always
    command: "-b 0.0.0.0 -Dkeycloak.import=/tmp/cms-realm.json"
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDRESS}
      DB_DATABASE: ${KEYCLOAK_DATABASE}
      DB_USER: ${KEYCLOAK_DATABASE_USER}
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING
    volumes:
      - "./config/realms-export-single-file.json:/tmp/cms-realm.json"
    networks:
      - sxcms