version: '3'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: sastix-cms-keycloak
    ports:
      - "127.0.0.1:${KEYCLOAK_PORT}:8080"
    environment:
      DB_VENDOR: ${DB_VENDOR}
      DB_ADDR: ${DB_ADDRESS}
      DB_DATABASE: ${KEYCLOAK_DATABASE}
      DB_USER: ${KEYCLOAK_DATABASE_USER}
      DB_PASSWORD: ${KEYCLOAK_DATABASE_PASSWORD}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
      JGROUPS_DISCOVERY_PROTOCOL: JDBC_PING